name: Flutter iOS CI/CD

on:
  push:
    branches:
      - main2

jobs:
  build_and_deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x.x'  # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build iOS
        run: flutter build ios --release --no-codesign

       - name: Build APK and IPA
        run: |
          flutter build apk --release
          flutter build ios --release --no-codesign

      - name: Archive APK and IPA
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/Runner.app
            
      - name: Deploy to iOS Device
        if: success()
        run: |
          # Specify the UDID of your iOS device
          UDID="<Your_iOS_Device_UDID>"
          flutter build ios
          xcrun instruments -w $UDID || true
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -destination "id=$UDID" build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/ios

      - name: Upload to TestFlight or App Store
        if: success()
        uses: v7labs/actions/appstore-connect-upload@v1
        with:
          apiKey: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
          issuerId: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          keyId: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          appId: ${{ secrets.APPSTORE_CONNECT_APP_ID }}
          groups: "Internal Testers"  # Modify as needed

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x.x'  # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test
