
name: CI/CD for IOS

on:
  push:
    branches:
      - DEV-IOS

permissions:
  id-token: write
  contents: read    


jobs:
  Authentication:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Import certificates (iOS)
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate and provisioning profile from secrets
          echo -n $BUILD_CERTIFICATE_BASE64 | base64 --decode --output $CERTIFICATE_PATH
          echo -n $BUILD_PROVISION_PROFILE_BASE64 | base64 --decode --output $PP_PATH
          
          # create a temporary keychain
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P $P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychains -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
  
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
      # 10   
    - uses: subosito/flutter-action@v2
      with:
          # 11
        flutter-version: "3.10.6"
        channel: 'stable'

    - name: Build iOS
      run: | 
        flutter build ipa --release --no-codesign
        /usr/bin/xcodebuild -version






    deploy:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Upload to TestFlight
        run: |
          # Assuming your IPA file is in the build/ios/ directory
          ipa_path=build/ios/Runner.ipa
          /usr/bin/xcrun altool --upload-app -f $ipa_path -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_ID_PASSWORD }}

          deploy:
  runs-on: macos-latest
  needs: build
  steps:
    - name: Upload to TestFlight
      run: |
        # Assuming your IPA file is in the build/ios/ directory
        ipa_path=$GITHUB_WORKSPACE/build/ios/Runner.ipa
        cd $GITHUB_WORKSPACE  # Change to the root directory of your repository

        /usr/bin/xcrun altool --upload-app -f $ipa_path -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_ID_PASSWORD }}


sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer


  - name: Build iOS
      run: |
        sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer
        xcodebuild -scheme "Runner" -archivePath $RUNNER_TEMP/ios/.xcarchive -sdk iphoneos -configuration Debug -destination generic/platform=iOS clean archive

         sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer
  xcodebuild -scheme "Runner" -archivePath $RUNNER_TEMP/ios/.xcarchive -sdk iphoneos -configuration Debug -destination generic/platform=iOS clean archive
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/12.0.2-3/x64
    JAVA_HOME_12_X64: /Users/runner/hostedtoolcache/Java_Zulu_jdk/12.0.2-3/x64
    FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.10.6-x64
    PUB_CACHE: /Users/runner/hostedtoolcache/flutter/stable-3.10.6-x64/.pub-cache
Command line invocation:
    /Applications/Xcode_14.2.app/Contents/Developer/usr/bin/xcodebuild -scheme Runner -archivePath /Users/runner/work/_temp/ios/.xcarchive -sdk iphoneos -configuration Debug -destination generic/platform=iOS clean archive

User defaults from command line:
    IDEArchivePathOverride = /Users/runner/work/_temp/ios/.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    SDKROOT = iphoneos16.2

2023-12-09 08:48:52.215 xcodebuild[1547:7381] Writing error result bundle to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2023-09-12_08-48-0052.xcresult
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project file 'Runner' was written by an unsupported Xcode version (0)



deploy:
  runs-on: macos-latest
  needs: build
  steps:
    - name: Upload to TestFlight
      run: |
        # Assuming your IPA file is in the build/ios/ directory
        ipa_path=$GITHUB_WORKSPACE/build/ios/Runner.ipa
        cd $GITHUB_WORKSPACE  # Change to the root directory of your repository

        /usr/bin/xcrun altool --upload-app -f $ipa_path -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_ID_PASSWORD }}
