name: Flutter CI/CD

on:
  push:
    branches:
      - maina

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Prerequisites setup on your local machine:
      - name: Set up Xcode
        run: |
          # Install Xcode on your local machine
          # Set up your Apple Developer Account in Xcode

      - name: Set up Flutter SDK
        run: |
          # Install Flutter SDK on your local machine
          # Add Flutter to your system PATH

      - name: Set up Cocoapods
        run: |
          # Install Cocoapods on your local machine

      - name: Set up iOS Simulator
        run: |
          # Open Xcode and set up iOS simulators

      - name: Set up Signing Certificates and Provisioning Profiles
        run: |
          # Set up signing certificates and provisioning profiles in Xcode

      - name: Set up Bundle Identifier, App Icons, and Launch Screens
        run: |
          # Configure your Flutter project with the correct bundle identifier, app icons, and launch screens

      - name: Set up Flutter Version Compatibility
        run: |
          # Ensure your Flutter project is compatible with the Flutter SDK version specified in your workflow

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x.x'  # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK and IPA
        run: |
          flutter build apk --release
          flutter build ios --release --no-codesign

      - name: Archive APK and IPA
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/Runner.app

  tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x.x'  # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  deploy_ios:
    runs-on: macos-latest

    needs: tests

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build

      - name: Deploy to TestFlight
        run: |
          # Specify the UDID of your iOS device
          UDID="<Your_iOS_Device_UDID>"
          xcrun instruments -w $UDID || true
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -destination "id=$UDID" archive -archivePath build/ios/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/ios/Runner.xcarchive -exportOptionsPlist export_options.plist -exportPath build/ios

  download_artifacts:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download APK and IPA Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Commit and Push Artifacts
        run: |
          git add build
          git commit -m "Add build artifacts"
          git push
